import { Component, OnInit, inject, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { PlacesService } from '../../core/services/places.service';
import { VenuesService } from '../../core/services/venues.service';
import { ManageNearbyPlaceRequest, NearbyPlace, VenueDto } from '../../core/models/api.models';
import { ConfirmDialogComponent } from '../../shared/components/confirm-dialog.component';

@Component({
  selector:'app-admin-places',
  standalone:true,
  imports:[FormsModule,DecimalPipe,ConfirmDialogComponent],
  template:`
  <div class="nv-page space-y-6">
    <div><p class="font-extrabold text-sm nv-muted">Nearby Discovery</p><h1 class="nv-page-title">Places</h1><p class="nv-muted mt-1">Manage nearby places against a selected venue so customer recommendations remain location-aware.</p></div>
    <section class="nv-card p-5"><label class="nv-label">Venue context</label><select class="nv-input max-w-xl" [(ngModel)]="venueId" (ngModelChange)="loadPlaces()" aria-label="Venue  id"><option value="">Select venue</option>@for(v of venues();track v.venueId){<option [value]="v.venueId">{{v.name}} · {{v.city}}</option>}</select></section>
    @if(venueId){<div class="grid xl:grid-cols-[420px_1fr] gap-5"><section class="nv-card p-5"><h2 class="font-black text-xl">{{editId?'Edit place':'Add place'}}</h2><form class="grid gap-3 mt-4" (ngSubmit)="save()"><input class="nv-input" name="name" [(ngModel)]="name" placeholder="Place name" required aria-label="Place name"><input class="nv-input" name="category" [(ngModel)]="category" placeholder="Category (Dining, Sightseeing...)" required aria-label="Category (Dining, Sightseeing...)"><input class="nv-input" name="address" [(ngModel)]="address" placeholder="Address" aria-label="Address"><div class="grid grid-cols-2 gap-2"><input class="nv-input" name="lat" type="number" step="any" [(ngModel)]="latitude" placeholder="Latitude" aria-label="Latitude"><input class="nv-input" name="lng" type="number" step="any" [(ngModel)]="longitude" placeholder="Longitude" aria-label="Longitude"></div><input class="nv-input" name="tags" [(ngModel)]="tags" placeholder="Tags, comma separated" aria-label="Tags, comma separated"><input class="nv-input" name="audience" [(ngModel)]="audience" placeholder="Audience: Couple, Friends, Family, Solo" aria-label="Audience: Couple, Friends, Family, Solo"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="open" [(ngModel)]="isOpen" aria-label="Open status"> Currently open / active</label><div class="flex gap-2"><button type="submit" class="nv-btn nv-btn-primary flex-1">{{editId?'Save Changes':'Add Place'}}</button>@if(editId){<button type="button" class="nv-btn nv-btn-secondary" (click)="resetForm()">Cancel</button>}</div></form></section><section class="space-y-3">@for(p of places();track p.id){<article class="nv-card p-5"><div class="flex flex-wrap justify-between gap-3"><div><span class="nv-status">{{p.category}}</span><h2 class="font-black text-xl mt-3">{{p.name}}</h2><p class="nv-muted text-sm mt-1">{{p.address||'No address provided'}}</p></div><div class="text-right"><div class="font-black">{{p.distanceKm|number:'1.1-1'}} km</div><div class="text-xs nv-muted">from venue</div></div></div><div class="flex flex-wrap gap-2 mt-4">@for(t of p.audienceModes||[];track t){<span class="nv-chip">{{t}}</span>}@for(t of p.tags||[];track t){<span class="nv-chip">{{t}}</span>}</div><div class="flex gap-2 mt-4"><button type="button" class="nv-btn nv-btn-secondary" (click)="edit(p)">Edit</button><button type="button" class="nv-btn nv-btn-secondary" (click)="remove(p)">Delete</button></div></article>}@empty{<div class="nv-card p-10 text-center nv-muted">No places are configured for this venue.</div>}</section></div>}
    @if(confirmation()){<app-confirm-dialog [title]="confirmation()!.title" [message]="confirmation()!.message" [confirmLabel]="confirmation()!.label" tone="danger" (confirmed)="runConfirmation()" (cancelled)="confirmation.set(null)"/>}
    @if(message()){<div class="fixed right-4 bottom-4 nv-card px-4 py-3" role="status">{{message()}}</div>}
  </div>`
})
export class AdminPlacesComponent implements OnInit{
  private venuesApi=inject(VenuesService);private placesApi=inject(PlacesService);venues=signal<VenueDto[]>([]);places=signal<NearbyPlace[]>([]);message=signal('');confirmation=signal<{title:string;message:string;label:string;action:()=>void}|null>(null);venueId='';editId='';name='';category='Sightseeing';address='';latitude:number|null=null;longitude:number|null=null;tags='';audience='Couple, Friends, Family, Solo';isOpen=true;
  ngOnInit(){this.venuesApi.list(1,100).subscribe({next:v=>this.venues.set(v),error:()=>this.venues.set([])});}
  loadPlaces(){if(!this.venueId){this.places.set([]);return;}this.placesApi.list(this.venueId).subscribe({next:v=>this.places.set(v),error:()=>this.places.set([])});}
  body():ManageNearbyPlaceRequest{const latitude=Number(this.latitude??0),longitude=Number(this.longitude??0);return{venueId:this.venueId,name:this.name.trim(),category:this.category.trim(),tags:this.csv(this.tags),audienceModes:this.csv(this.audience),address:this.address.trim(),distanceKm:this.distanceFromVenue(latitude,longitude),latitude,longitude,isOpen:this.isOpen,directionsUrl:null,isActive:true};}
  save(){if(!this.venueId||!this.name.trim())return;const request=this.editId?this.placesApi.update(this.editId,this.body()):this.placesApi.create(this.body());request.subscribe({next:()=>{this.message.set(this.editId?'Place updated.':'Place created.');this.resetForm();this.loadPlaces();},error:e=>this.message.set(e?.error?.message||e?.error?.error||'Place could not be saved.')});}
  edit(p:NearbyPlace){this.editId=p.id;this.name=p.name;this.category=p.category;this.address=p.address;this.latitude=p.latitude;this.longitude=p.longitude;this.tags=(p.tags||[]).join(', ');this.audience=(p.audienceModes||[]).join(', ');this.isOpen=p.isOpen;}
  remove(p:NearbyPlace){this.confirmation.set({title:'Delete this place?',message:`${p.name} will be removed from nearby-place recommendations.`,label:'Delete Place',action:()=>this.placesApi.remove(p.id).subscribe({next:()=>{this.message.set('Place deleted.');this.loadPlaces();},error:e=>this.message.set(e?.error?.message||'Place could not be deleted.')})});}
  runConfirmation(){const current=this.confirmation();this.confirmation.set(null);current?.action();}
  resetForm(){this.editId='';this.name='';this.category='Sightseeing';this.address='';this.latitude=null;this.longitude=null;this.tags='';this.audience='Couple, Friends, Family, Solo';this.isOpen=true;}
  distanceFromVenue(lat:number,lng:number){const v=this.venues().find(x=>x.venueId===this.venueId);if(v?.latitude==null||v?.longitude==null||!Number.isFinite(lat)||!Number.isFinite(lng))return 0;const r=6371;const toRad=(n:number)=>n*Math.PI/180;const dLat=toRad(lat-Number(v.latitude)),dLng=toRad(lng-Number(v.longitude));const a=Math.sin(dLat/2)**2+Math.cos(toRad(Number(v.latitude)))*Math.cos(toRad(lat))*Math.sin(dLng/2)**2;return Math.round((2*r*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)))*100)/100;}
  csv(value:string){return value.split(',').map(x=>x.trim()).filter(Boolean);}
}
