import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ParkingService } from '../../core/services/parking.service';
import { VenuesService } from '../../core/services/venues.service';
import { ParkingSlot, ParkingZone, UpsertParkingSlotRequest, VenueDto } from '../../core/models/api.models';

@Component({
  selector:'app-admin-parking',
  standalone:true,
  imports:[FormsModule],
  template:`
  <div class="nv-page space-y-6">
    <div><p class="font-extrabold text-sm nv-muted">Parking Management</p><h1 class="nv-page-title">Parking</h1><p class="nv-muted mt-1">Inspect and manage parking zones and slots for a selected venue. Admin is authorized as a parking manager.</p></div>
    <section class="nv-card p-5"><label class="nv-label">Venue</label><select class="nv-input max-w-xl" [(ngModel)]="venueId" (ngModelChange)="loadZones()" aria-label="Venue  id"><option value="">Select venue</option>@for(v of venues();track v.venueId){<option [value]="v.venueId">{{v.name}} · {{v.city}}</option>}</select></section>
    @if(venueId){<div class="grid xl:grid-cols-[380px_1fr] gap-5"><section class="space-y-4"><div class="nv-card p-5"><h2 class="font-black text-lg">Create zone</h2><div class="grid gap-3 mt-4"><input class="nv-input" [(ngModel)]="zoneName" placeholder="Zone name" aria-label="Zone name"><input class="nv-input" [(ngModel)]="zoneLevel" placeholder="Level" aria-label="Level"><input class="nv-input" [(ngModel)]="entranceName" placeholder="Entrance" aria-label="Entrance"><button type="button" class="nv-btn nv-btn-primary" (click)="addZone()">Add Zone</button></div></div><div class="nv-card p-4"><h2 class="font-black">Zones</h2><div class="space-y-2 mt-3">@for(z of zones();track z.id){<button type="button" class="w-full nv-card-soft p-4 text-left" [style.borderColor]="zoneId===z.id?'var(--focus)':'var(--border)'" (click)="selectZone(z)"><div class="font-extrabold">{{z.name}}</div><div class="nv-muted text-sm mt-1">{{z.level}} · {{z.entranceName}}</div></button>}@empty{<div class="nv-muted text-sm py-5">No zones configured.</div>}</div></div></section><section class="nv-card p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-black text-xl">Slots</h2><p class="nv-muted text-sm mt-1">{{selectedZone()?.name||'Choose a zone'}} · {{slots().length}} configured slot{{slots().length===1?'':'s'}}</p></div>@if(zoneId){<div class="flex flex-wrap gap-2"><input class="nv-input w-24" type="number" min="1" max="26" [(ngModel)]="rows" aria-label="Rows"><input class="nv-input w-24" type="number" min="1" max="99" [(ngModel)]="cols" aria-label="Columns"><input class="nv-input w-28" type="number" min="0" [(ngModel)]="accessibleSlots" aria-label="Accessible slots" placeholder="Accessible"><button type="button" class="nv-btn nv-btn-secondary" (click)="generate()">Generate</button></div>}</div>@if(zoneId){<div class="relative h-[520px] rounded-3xl overflow-hidden mt-5 border" style="background:linear-gradient(145deg,var(--surface-2),var(--surface-3));border-color:var(--border)">@for(s of slots();track s.id){<div class="absolute w-14 h-10 rounded-xl border grid place-items-center text-[10px] font-black" [style.left.%]="x(s)" [style.top.%]="y(s)" [style.background]="slotBg(s)" [style.borderColor]="s.isAccessible?'var(--info)':'var(--border)'">{{s.slotCode}}</div>}</div>}@else{<div class="py-20 text-center nv-muted">Choose a parking zone to view its visual slot layout.</div>}</section></div>}
    @if(message()){<div class="fixed right-4 bottom-4 nv-card px-4 py-3" role="status">{{message()}}</div>}
  </div>`
})
export class AdminParkingComponent implements OnInit{
  private venuesApi=inject(VenuesService);private parking=inject(ParkingService);venues=signal<VenueDto[]>([]);zones=signal<ParkingZone[]>([]);slots=signal<ParkingSlot[]>([]);venueId='';zoneId='';zoneName='Zone A';zoneLevel='Ground';entranceName='Main Gate';rows=5;cols=8;accessibleSlots=0;message=signal('');
  ngOnInit(){this.venuesApi.list(1,100).subscribe({next:v=>this.venues.set(v),error:()=>this.venues.set([])});}
  loadZones(){this.zoneId='';this.slots.set([]);if(!this.venueId){this.zones.set([]);return;}this.parking.zones(this.venueId).subscribe({next:v=>{this.zones.set(v);if(v.length)this.selectZone(v[0]);},error:()=>this.zones.set([])});}
  selectZone(z:ParkingZone){this.zoneId=z.id;this.parking.slots(z.id).subscribe({next:v=>this.slots.set(v),error:()=>this.slots.set([])});}
  selectedZone(){return this.zones().find(z=>z.id===this.zoneId)??null;}
  addZone(){if(!this.venueId||!this.zoneName.trim())return;this.parking.zonesCreate({venueId:this.venueId,eventId:null,name:this.zoneName.trim(),level:this.zoneLevel.trim(),entranceName:this.entranceName.trim()}).subscribe({next:()=>{this.message.set('Parking zone created.');this.loadZones();},error:e=>this.message.set(e?.error?.message||e?.error?.error||'Parking zone could not be created.')});}
  generate(){if(!this.zoneId)return;const slots:UpsertParkingSlotRequest[]=[];const rows=Math.max(1,Math.min(26,Number(this.rows)));const cols=Math.max(1,Math.min(99,Number(this.cols)));const accessible=Math.max(0,Math.min(rows*cols,Number(this.accessibleSlots)||0));for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const index=r*cols+c;slots.push({parkingZoneId:this.zoneId,eventId:null,slotCode:`${String.fromCharCode(65+r)}${c+1}`,x:8+c*(84/Math.max(1,cols-1)),y:8+r*(82/Math.max(1,rows-1)),isAccessible:index<accessible});}this.parking.slotsBulk({slots}).subscribe({next:()=>{this.message.set('Parking slots generated.');const z=this.selectedZone();if(z)this.selectZone(z);},error:e=>this.message.set(e?.error?.message||e?.error?.error||'Slots could not be generated.')});}
  x(s:ParkingSlot){return Math.max(0,Math.min(90,Number(s.x)||0));}y(s:ParkingSlot){return Math.max(0,Math.min(92,Number(s.y)||0));}slotBg(s:ParkingSlot){const status=String(s.status||'').toLowerCase();return status.includes('available')?'var(--surface)':status.includes('occupied')||status.includes('reserved')?'#444E6D':'var(--surface-2)';}
}
