import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { DecimalPipe } from '@angular/common';
import { BookingsService } from '../../core/services/bookings.service';
import { BookingDto, PayHereCheckoutDto, PaymentDto } from '../../core/models/api.models';
import { PageStateComponent } from '../../shared/components/page-state.component';
@Component({selector:'app-payment-page',standalone:true,imports:[RouterLink,DecimalPipe,PageStateComponent],template:`
<div class="nv-page max-w-5xl">@if(loading()){<div class="nv-skeleton h-96"></div>}@else if(!booking()){<app-page-state kind="error" title="Booking unavailable" message="This booking could not be loaded."/>}@else{<div class="grid lg:grid-cols-[1fr_340px] gap-5"><section class="nv-card p-6"><p class="text-sm font-extrabold nv-muted">Checkout</p><h1 class="nv-page-title mt-1">Complete payment</h1><p class="nv-muted mt-2">Booking {{booking()!.bookingNumber}}</p><div class="nv-card-soft p-5 mt-6"><div class="flex justify-between gap-3"><span>Seats</span><strong>{{booking()!.seatIds.length}}</strong></div><div class="flex justify-between gap-3 mt-3"><span>Status</span><strong>{{statusLabel}}</strong></div><div class="border-t mt-4 pt-4 flex justify-between text-lg" style="border-color:var(--border)"><strong>Total</strong><strong>LKR {{booking()!.totalAmount|number:'1.0-2'}}</strong></div></div>@if(payment()){<div class="mt-6 p-4 rounded-2xl" style="background:color-mix(in srgb,var(--info) 10%,var(--surface));border:1px solid color-mix(in srgb,var(--info) 30%,var(--border))"><h2 class="font-black">Payment started</h2><p class="nv-muted text-sm mt-1">Payment reference: {{payment()!.paymentId}}</p></div>}@if(message()){<p class="mt-4 text-sm" [style.color]="error()?'var(--danger)':'var(--success)'">{{message()}}</p>}</section><aside class="nv-card p-5 h-fit"><h2 class="font-black text-lg">Payment options</h2><p class="nv-muted text-sm mt-2">Continue securely with the configured PayHere checkout.</p><button type="button" class="nv-btn nv-btn-primary w-full mt-5" [disabled]="busy()" (click)="payHere()">{{busy()?'Preparing checkout...':'Pay with PayHere'}}</button><a routerLink="/app/bookings" class="nv-btn nv-btn-secondary w-full mt-3">Return to Bookings</a></aside></div>}</div>`})
export class PaymentPageComponent implements OnInit{private route=inject(ActivatedRoute);private router=inject(Router);private api=inject(BookingsService);bookingId='';booking=signal<BookingDto|null>(null);payment=signal<PaymentDto|null>(null);loading=signal(true);busy=signal(false);message=signal('');error=signal(false);get statusLabel(){return ['Pending','Confirmed','Cancelled','Completed'][this.booking()?.status??0]??'Booking';}ngOnInit(){this.bookingId=this.route.snapshot.paramMap.get('bookingId')!;this.api.get(this.bookingId).subscribe({next:b=>{this.booking.set(b);this.loading.set(false);if(b.status===1)void this.router.navigate(['/app/tickets']);},error:()=>this.loading.set(false)});}payHere(){this.busy.set(true);this.error.set(false);this.api.startPayment({bookingId:this.bookingId}).subscribe({next:p=>{this.payment.set(p);this.api.payHere(p.paymentId).subscribe({next:c=>{this.busy.set(false);if(c?.checkoutUrl){this.submitPayHere(c);}else{this.message.set('Checkout information was created, but no checkout URL was returned.');}},error:e=>{this.busy.set(false);this.error.set(true);this.message.set(e?.error?.message||'PayHere checkout could not be prepared.');}});},error:e=>{this.busy.set(false);this.error.set(true);this.message.set(e?.error?.message||'Payment could not be started.');}});}private submitPayHere(c:PayHereCheckoutDto){const form=document.createElement('form');form.method='POST';form.action=c.checkoutUrl;const fields:Record<string,unknown>={merchant_id:c.merchantId,return_url:c.returnUrl,cancel_url:c.cancelUrl,notify_url:c.notifyUrl,first_name:c.firstName,last_name:c.lastName,email:c.email,phone:c.phone,address:c.address,city:c.city,country:c.country,order_id:c.orderId,items:c.items,currency:c.currency,amount:c.amount,hash:c.hash};for(const[k,v]of Object.entries(fields)){const i=document.createElement('input');i.type='hidden';i.name=k;i.value=String(v??'');form.appendChild(i);}document.body.appendChild(form);form.submit();}}
