import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { PlacesService } from '../../core/services/places.service';
import { VenuesService } from '../../core/services/venues.service';
import { NearbyPlace, VenueDto } from '../../core/models/api.models';
import { PageStateComponent } from '../../shared/components/page-state.component';
import { PlaceCardComponent } from '../../shared/components/place-card.component';
@Component({selector:'app-places-page',standalone:true,imports:[FormsModule,PageStateComponent,PlaceCardComponent],template:`
<div class="nv-page space-y-6"><section class="nv-hero nv-photo-hero nv-places-hero min-h-[220px] text-white"><div class="nv-photo-hero-overlay"></div><div class="relative z-10"><p class="font-extrabold text-sm opacity-75">Place Finder</p><h1 class="nv-page-title mt-1">Explore Places</h1><p class="mt-2 opacity-80">Recommendations around a venue for couples, friends, families or solo visitors.</p></div></section>
<section class="nv-card p-4"><div class="grid lg:grid-cols-[1fr_auto] gap-3 items-end"><div><label class="nv-label">Venue context</label><select class="nv-input" [(ngModel)]="venueId" (ngModelChange)="load()" aria-label="Venue  id"><option value="">Select venue</option>@for(v of venues();track v.venueId){<option [value]="v.venueId">{{v.name}}</option>}</select></div><div class="flex flex-wrap gap-2">@for(a of audiences;track a){<button type="button" class="nv-chip" [class.active]="audience===a" (click)="audience=a;load()">{{a}}</button>}</div></div><div class="flex flex-wrap gap-2 mt-4">@for(c of categories;track c){<button type="button" class="nv-chip" [class.active]="category===c" (click)="category=c;load()">{{c}}</button>}<select class="nv-chip" [(ngModel)]="maxDistance" (ngModelChange)="load()" aria-label="Max distance"><option [ngValue]="null">Any distance</option><option [ngValue]="2">Within 2 km</option><option [ngValue]="5">Within 5 km</option><option [ngValue]="10">Within 10 km</option></select></div></section>
@if(venueError()){<app-page-state kind="error" title="We couldn't load venues" message="Venue context is required for nearby recommendations. Please refresh the page and try again."/>}
@else if(!venueId){<app-page-state title="Choose a venue" message="Nearby recommendations need a venue context before distance and directions are meaningful."/>}
@else if(loading()){<div class="nv-skeleton h-96"></div>}
@else if(error()){<app-page-state kind="error" title="We couldn't load nearby places" message="Please try the recommendation again." actionLabel="Retry" [action]="retry"/>}
@else if(places().length){<div class="grid xl:grid-cols-[1fr_420px] gap-5"><section><div class="grid md:grid-cols-2 gap-4">@for(p of places();track p.id){<app-place-card [place]="p"/>}</div></section><aside class="nv-card p-4 h-fit xl:sticky xl:top-5"><h2 class="font-black text-lg">Map overview</h2><p class="nv-muted text-sm mt-1">See recommended places around the selected venue.</p><div class="relative h-[460px] rounded-2xl mt-4 overflow-hidden" style="background:linear-gradient(135deg,var(--surface-2),var(--surface-3))"><div class="absolute inset-0 opacity-30" style="background-image:linear-gradient(var(--border) 1px,transparent 1px),linear-gradient(90deg,var(--border) 1px,transparent 1px);background-size:32px 32px"></div>@for(p of places();track p.id){<a [href]="osm(p)" target="_blank" rel="noopener" class="absolute w-9 h-9 rounded-full grid place-items-center text-xs font-black text-white shadow-lg" [style.left.%]="mapX(p)" [style.top.%]="mapY(p)" style="background:var(--primary)" [attr.aria-label]="'Open '+p.name+' on map'">⌖</a>}</div></aside></div>}@else{<app-page-state title="No matching places" message="Try another group type, category or distance filter."/>}
</div>`})
export class PlacesPageComponent implements OnInit{private api=inject(PlacesService);private venuesApi=inject(VenuesService);private route=inject(ActivatedRoute);venues=signal<VenueDto[]>([]);places=signal<NearbyPlace[]>([]);loading=signal(false);error=signal(false);venueError=signal(false);venueId='';audience='Friends';category='All';maxDistance:number|null=null;audiences=['Couple','Friends','Family','Solo'];categories=['All','Dining','Entertainment','Sightseeing','Activities','Shopping','Photo Spots','Relaxation'];retry=()=>this.load();ngOnInit(){this.route.queryParamMap.subscribe(params=>{this.venueId=params.get('venue')??'';this.category=params.get('category')??'All';if(this.venues().length&&this.venueId)this.load();});this.venuesApi.list().subscribe({next:v=>{this.venues.set(v);this.venueError.set(false);if(!this.venueId&&v.length===1)this.venueId=v[0].venueId;if(this.venueId)this.load();},error:()=>this.venueError.set(true)});}load(){if(!this.venueId){this.places.set([]);this.error.set(false);return;}this.loading.set(true);this.error.set(false);this.api.recommendations(this.venueId,{audienceMode:this.audience,category:this.category==='All'?undefined:this.category,maxDistanceKm:this.maxDistance??undefined,includeClosed:false}).subscribe({next:v=>{this.places.set(v);this.loading.set(false);},error:()=>{this.places.set([]);this.error.set(true);this.loading.set(false);}});}osm(p:NearbyPlace){return `https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}`;}mapX(p:NearbyPlace){const xs=this.places().map(x=>Number(x.longitude));const min=Math.min(...xs),max=Math.max(...xs);return max===min?50:8+((Number(p.longitude)-min)/(max-min))*84;}mapY(p:NearbyPlace){const ys=this.places().map(x=>Number(x.latitude));const min=Math.min(...ys),max=Math.max(...ys);return max===min?50:8+(1-(Number(p.latitude)-min)/(max-min))*84;}}
