import { Component, ElementRef, HostListener, OnInit, ViewChild, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DatePipe, DecimalPipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { forkJoin, of, catchError } from 'rxjs';
import { AccountService } from '../../core/services/account.service';
import { ParkingService } from '../../core/services/parking.service';
import { BookingsService } from '../../core/services/bookings.service';
import { AuthService } from '../../core/services/auth.service';
import { ThemeService } from '../../core/services/theme.service';
import { ReceiptDeliveryDto, ReceiptDto, USER_ROLE, UserProfile, VehicleDto, roleLabel } from '../../core/models/api.models';
import { PageStateComponent } from '../../shared/components/page-state.component';
import { ConfirmDialogComponent } from '../../shared/components/confirm-dialog.component';

@Component({
  selector:'app-profile-page',
  standalone:true,
  imports:[FormsModule,RouterLink,DatePipe,DecimalPipe,PageStateComponent,ConfirmDialogComponent],
  template:`
  <div class="nv-page space-y-6">
    @if(loading()){
      <div class="nv-skeleton h-96"></div>
    } @else if(!profile()){
      <app-page-state kind="error" title="Profile unavailable" message="Please sign in again to load your profile."/>
    } @else {
      <section class="nv-hero nv-profile-hero min-h-[210px]"><div class="relative z-10 flex flex-col sm:flex-row sm:items-center gap-5"><div class="w-20 h-20 rounded-full grid place-items-center text-2xl font-black text-white border-4 border-white/40" style="background:linear-gradient(135deg,#665A88,#E49C95)">{{initials}}</div><div><p class="font-extrabold text-sm opacity-75">Profile</p><h1 class="text-3xl sm:text-4xl font-black tracking-[-.04em]">{{profile()!.name}}</h1><p class="opacity-80 mt-1">{{profile()!.email}} · {{roleLabel(profile()!.role)}}</p></div></div></section>

      <div class="grid xl:grid-cols-[1fr_360px] gap-5">
        <div class="space-y-5">
          <section class="nv-card p-6">
            <div class="flex justify-between gap-4 items-center"><h2 class="text-xl font-black">Account Information</h2><button type="button" class="nv-btn nv-btn-secondary" (click)="editing.set(!editing())">{{editing()?'Cancel':'Edit'}}</button></div>
            @if(editing()){
              <form class="grid sm:grid-cols-2 gap-4 mt-5" (ngSubmit)="save()"><div><label class="nv-label">First name</label><input class="nv-input" name="first" [(ngModel)]="firstName" required aria-label="First name"></div><div><label class="nv-label">Last name</label><input class="nv-input" name="last" [(ngModel)]="lastName" aria-label="Last name"></div><div class="sm:col-span-2"><label class="nv-label">Phone</label><input class="nv-input" name="phone" [(ngModel)]="phone" aria-label="Phone"></div><button type="submit" class="nv-btn nv-btn-primary sm:col-span-2" [disabled]="busy()">{{busy()?'Saving...':'Save Changes'}}</button></form>
            } @else {
              <dl class="grid sm:grid-cols-2 gap-4 mt-5"><div class="nv-card-soft p-4"><dt class="text-sm nv-muted">Email</dt><dd class="font-extrabold mt-1 break-all">{{profile()!.email}}</dd></div><div class="nv-card-soft p-4"><dt class="text-sm nv-muted">Phone</dt><dd class="font-extrabold mt-1">{{profile()!.phoneNumber||'Not provided'}}</dd></div><div class="nv-card-soft p-4"><dt class="text-sm nv-muted">Role</dt><dd class="font-extrabold mt-1">{{roleLabel(profile()!.role)}}</dd></div><div class="nv-card-soft p-4"><dt class="text-sm nv-muted">Theme</dt><dd class="font-extrabold mt-1 capitalize">{{theme.mode()}}</dd></div></dl>
            }
          </section>

          @if(isCustomer){
            <section class="nv-card p-6"><div class="flex justify-between gap-4 items-center"><div><h2 class="text-xl font-black">Saved Vehicles</h2><p class="nv-muted text-sm mt-1">Used when reserving parking.</p></div><button type="button" class="nv-btn nv-btn-secondary" (click)="vehicleForm.set(!vehicleForm())">Add Vehicle</button></div>
              @if(vehicleForm()){<form class="grid sm:grid-cols-2 gap-3 mt-4" (ngSubmit)="addVehicle()"><input class="nv-input" name="nick" [(ngModel)]="vehicleNickname" placeholder="Nickname" aria-label="Nickname"><input class="nv-input" name="reg" [(ngModel)]="vehicleRegistration" placeholder="Registration number" required aria-label="Registration number"><input class="nv-input" name="type" [(ngModel)]="vehicleType" placeholder="Vehicle type" aria-label="Vehicle type"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="default" [(ngModel)]="vehicleDefault" aria-label="Set as default vehicle"> Set as default</label><button type="submit" class="nv-btn nv-btn-primary sm:col-span-2">Save Vehicle</button></form>}
              <div class="space-y-3 mt-4">@for(v of vehicles();track v.id){<div class="nv-card-soft p-4 flex justify-between items-center gap-3"><div><div class="font-extrabold">{{v.nickname||v.vehicleType}}</div><div class="nv-muted text-sm">{{v.registrationNo}} · {{v.vehicleType}}</div></div><div class="flex items-center gap-2">@if(v.isDefault){<span class="nv-status">Primary</span>}<button type="button" class="text-sm nv-muted" (click)="removeVehicle(v)">Remove</button></div></div>}@empty{<p class="nv-muted text-sm">No saved vehicles yet.</p>}</div>
            </section>

            <section class="nv-card p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-black">Receipts</h2><p class="nv-muted text-sm mt-1">Payment receipts stored in your Nvent account.</p></div><span class="nv-status">{{receipts().length}} total</span></div>@if(receipts().length){<div class="grid md:grid-cols-2 gap-3 mt-4">@for(r of receipts();track r.receiptId){<article class="nv-card-soft p-4"><div class="flex justify-between gap-3"><div><div class="font-black">{{r.receiptNumber}}</div><div class="text-xs nv-muted mt-1">{{r.issuedAtUtc|date:'medium'}}</div></div><div class="font-black">{{r.currency}} {{r.amount|number:'1.0-2'}}</div></div><div class="flex flex-wrap gap-2 mt-4"><button type="button" class="nv-btn nv-btn-secondary" (click)="showReceipt(r)">Delivery Status</button><button type="button" class="nv-btn nv-btn-secondary" (click)="retryReceipt(r)">Retry Delivery</button></div></article>}</div>}@else{<p class="nv-muted text-sm mt-4">No receipts have been generated yet.</p>}</section>
          }

          <section class="nv-card p-6"><h2 class="text-xl font-black">Security</h2><form class="grid sm:grid-cols-2 gap-3 mt-4" (ngSubmit)="changePassword()"><div class="relative"><input class="nv-input pr-12" [type]="currentPasswordVisible?'text':'password'" name="current" [(ngModel)]="currentPassword" placeholder="Current password" autocomplete="current-password" required aria-label="Current password"><button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 grid place-items-center rounded-lg nv-muted hover:text-[var(--text)]" (click)="currentPasswordVisible=!currentPasswordVisible" [attr.aria-label]="currentPasswordVisible?'Hide current password':'Show current password'" [attr.title]="currentPasswordVisible?'Hide current password':'Show current password'" [attr.aria-pressed]="currentPasswordVisible"><svg aria-hidden="true" viewBox="0 0 24 24" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">@if(currentPasswordVisible){<path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5 0 8.5 4.5 9.5 6a2 2 0 0 1 0 2 15.7 15.7 0 0 1-2.4 2.9"/><path d="M6.6 6.6A16.2 16.2 0 0 0 2.5 10a2 2 0 0 0 0 2c1 1.5 4.5 6 9.5 6 1 0 2-.2 2.9-.5"/>}@else{<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6S2.5 12 2.5 12z"/><circle cx="12" cy="12" r="2.5"/>}</svg></button></div><div class="relative"><input class="nv-input pr-12" [type]="newPasswordVisible?'text':'password'" name="new" [(ngModel)]="newPassword" placeholder="New password" autocomplete="new-password" required aria-label="New password"><button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 grid place-items-center rounded-lg nv-muted hover:text-[var(--text)]" (click)="newPasswordVisible=!newPasswordVisible" [attr.aria-label]="newPasswordVisible?'Hide new password':'Show new password'" [attr.title]="newPasswordVisible?'Hide new password':'Show new password'" [attr.aria-pressed]="newPasswordVisible"><svg aria-hidden="true" viewBox="0 0 24 24" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">@if(newPasswordVisible){<path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5 0 8.5 4.5 9.5 6a2 2 0 0 1 0 2 15.7 15.7 0 0 1-2.4 2.9"/><path d="M6.6 6.6A16.2 16.2 0 0 0 2.5 10a2 2 0 0 0 0 2c1 1.5 4.5 6 9.5 6 1 0 2-.2 2.9-.5"/>}@else{<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6S2.5 12 2.5 12z"/><circle cx="12" cy="12" r="2.5"/>}</svg></button></div><button type="submit" class="nv-btn nv-btn-secondary sm:col-span-2">Change Password</button></form></section>
        </div>

        <aside class="space-y-4">
          <section class="nv-card p-5"><h2 class="font-black">{{isCustomer?'Account Hub':'Workspace'}}</h2><div class="grid gap-2 mt-4">@for(link of hubLinks;track link.path){<a [routerLink]="link.path" class="nv-card-soft p-3 font-extrabold">{{link.label}}</a>}</div></section>
          <section class="nv-card p-5"><h2 class="font-black">Preferences</h2><label class="nv-label mt-4">Theme</label><select class="nv-input" [ngModel]="theme.mode()" (ngModelChange)="theme.set($event)" name="theme" aria-label="Theme"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></section>
          @if(isCustomer){<section class="nv-card p-5"><h2 class="font-black">Payments & Receipts</h2><p class="nv-muted text-sm mt-2">{{receipts().length}} receipt{{receipts().length===1?'':'s'}} available in your account.</p></section>}
        </aside>
      </div>
      @if(confirmation()){<app-confirm-dialog [title]="confirmation()!.title" [message]="confirmation()!.message" [confirmLabel]="confirmation()!.label" tone="danger" (confirmed)="runConfirmation()" (cancelled)="confirmation.set(null)"/>}
      @if(openReceipt()){<div class="fixed inset-0 z-[95] bg-black/50 p-4 grid place-items-center" (click)="closeReceipt()"><section #receiptDialog class="nv-card p-5 sm:p-6 max-w-lg w-full" role="dialog" aria-modal="true" aria-labelledby="receipt-delivery-title" (click)="$event.stopPropagation()"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-extrabold nv-muted">Receipt delivery</p><h2 id="receipt-delivery-title" class="text-2xl font-black mt-1">{{openReceipt()!.receiptNumber}}</h2></div><button #receiptClose type="button" class="w-11 h-11 rounded-xl" (click)="closeReceipt()" aria-label="Close receipt delivery">×</button></div><div class="space-y-3 mt-5">@for(d of receiptDeliveries();track d.receiptDeliveryId){<div class="nv-card-soft p-4"><div class="flex justify-between gap-3"><div class="font-black">{{d.channel}}</div><span class="nv-status">{{d.status}}</span></div><div class="text-sm nv-muted mt-2">{{d.destinationMasked||'Protected destination'}}</div><div class="text-xs nv-muted mt-1">Attempts: {{d.attemptCount}} @if(d.sentAtUtc){<span>· Sent {{d.sentAtUtc|date:'medium'}}</span>}</div>@if(d.lastError){<div class="text-xs mt-2" style="color:var(--danger)">{{d.lastError}}</div>}</div>}@empty{<p class="nv-muted text-sm">No delivery records were returned for this receipt.</p>}</div></section></div>}
      @if(message()){<div class="fixed right-4 bottom-24 lg:bottom-4 nv-card px-4 py-3 text-sm" role="status">{{message()}}</div>}
    }
  </div>`
})
export class ProfilePageComponent implements OnInit{
  @ViewChild('receiptDialog') receiptDialog?:ElementRef<HTMLElement>;
  @ViewChild('receiptClose') receiptClose?:ElementRef<HTMLButtonElement>;
  private receiptReturnFocus:HTMLElement|null=null;

  private account=inject(AccountService);private parking=inject(ParkingService);private bookings=inject(BookingsService);private auth=inject(AuthService);theme=inject(ThemeService);
  profile=signal<UserProfile|null>(null);vehicles=signal<VehicleDto[]>([]);receipts=signal<ReceiptDto[]>([]);confirmation=signal<{title:string;message:string;label:string;action:()=>void}|null>(null);receiptDeliveries=signal<ReceiptDeliveryDto[]>([]);openReceipt=signal<ReceiptDto|null>(null);loading=signal(true);editing=signal(false);vehicleForm=signal(false);busy=signal(false);message=signal('');
  firstName='';lastName='';phone='';vehicleNickname='';vehicleRegistration='';vehicleType='Car';vehicleDefault=false;currentPassword='';newPassword='';currentPasswordVisible=false;newPasswordVisible=false;roleLabel=roleLabel;
  get initials(){return this.profile()?.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()||'NV';}
  get isCustomer(){return this.profile()?.role===USER_ROLE.Customer;}
  get hubLinks(){switch(this.profile()?.role){case USER_ROLE.EventOrganizer:return[{label:'Organizer Dashboard',path:'/organizer'},{label:'My Events',path:'/organizer/events'},{label:'Stage & Seating',path:'/organizer/seating'},{label:'Analytics',path:'/organizer/analytics'}];case USER_ROLE.VenueOwner:return[{label:'Venue Dashboard',path:'/venue-owner'},{label:'My Venues',path:'/venue-owner/venues'},{label:'Rental Requests',path:'/venue-owner/rentals'},{label:'Reports',path:'/venue-owner/reports'}];case USER_ROLE.Admin:return[{label:'Admin Dashboard',path:'/admin'},{label:'Users',path:'/admin/users'},{label:'Audit Logs',path:'/admin/audit-logs'},{label:'Reports',path:'/admin/reports'}];default:return[{label:'My Tickets',path:'/app/tickets'},{label:'My Bookings',path:'/app/bookings'},{label:'Parking Reservations',path:'/app/parking'},{label:'Food Orders',path:'/app/food'}];}}
  ngOnInit(){const customer=this.auth.role()===USER_ROLE.Customer;forkJoin({profile:this.account.me(),vehicles:customer?this.parking.vehicles().pipe(catchError(()=>of([]))):of([]),receipts:customer?this.bookings.receipts().pipe(catchError(()=>of([]))):of([])}).subscribe({next:v=>{this.profile.set(v.profile);this.vehicles.set(v.vehicles as VehicleDto[]);this.receipts.set(v.receipts as ReceiptDto[]);const parts=v.profile.name.trim().split(/\s+/);this.firstName=parts.shift()??'';this.lastName=parts.join(' ');this.phone=v.profile.phoneNumber??'';this.loading.set(false);},error:()=>this.loading.set(false)});}
  save(){this.busy.set(true);this.account.update({firstName:this.firstName,lastName:this.lastName,phoneNumber:this.phone||null}).subscribe({next:v=>{this.profile.set(v);this.editing.set(false);this.busy.set(false);this.message.set('Profile updated.');},error:e=>{this.busy.set(false);this.message.set(e?.error?.message||'Profile could not be updated.');}});}
  addVehicle(){this.parking.addVehicle({nickname:this.vehicleNickname,registrationNo:this.vehicleRegistration,vehicleType:this.vehicleType,isDefault:this.vehicleDefault}).subscribe({next:v=>{this.vehicles.update(xs=>[...xs,v]);this.vehicleForm.set(false);this.vehicleNickname='';this.vehicleRegistration='';this.message.set('Vehicle saved.');},error:e=>this.message.set(e?.error?.message||'Vehicle could not be saved.')});}
  removeVehicle(v:VehicleDto){this.confirmation.set({title:'Remove saved vehicle?',message:`${v.nickname||v.registrationNo} will be removed from your parking profile.`,label:'Remove Vehicle',action:()=>this.parking.removeVehicle(v.id).subscribe({next:()=>this.vehicles.update(xs=>xs.filter(x=>x.id!==v.id)),error:e=>this.message.set(e?.error?.message||'Vehicle could not be removed.')})});}
  runConfirmation(){const current=this.confirmation();this.confirmation.set(null);current?.action();}
  changePassword(){this.account.password(this.currentPassword,this.newPassword).subscribe({next:()=>{this.currentPassword='';this.newPassword='';this.message.set('Password changed.');},error:e=>this.message.set(e?.error?.message||'Password could not be changed.')});}
  showReceipt(receipt:ReceiptDto){this.receiptReturnFocus=document.activeElement as HTMLElement|null;this.openReceipt.set(receipt);setTimeout(()=>this.receiptClose?.nativeElement.focus());this.receiptDeliveries.set([]);this.bookings.receiptDeliveries(receipt.receiptId).subscribe({next:v=>this.receiptDeliveries.set(v),error:()=>this.receiptDeliveries.set([])});}
  closeReceipt(){this.openReceipt.set(null);this.receiptDeliveries.set([]);const target=this.receiptReturnFocus;this.receiptReturnFocus=null;setTimeout(()=>target?.focus());}
  @HostListener('document:keydown',['$event']) onReceiptDialogKeydown(event:KeyboardEvent){if(!this.openReceipt())return;if(event.key==='Escape'){event.preventDefault();this.closeReceipt();return;}if(event.key!=='Tab'||!this.receiptDialog)return;const nodes=Array.from(this.receiptDialog.nativeElement.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  retryReceipt(receipt:ReceiptDto){this.receiptReturnFocus=document.activeElement as HTMLElement|null;this.bookings.retryReceipt(receipt.receiptId).subscribe({next:v=>{this.receiptDeliveries.set(v);this.openReceipt.set(receipt);setTimeout(()=>this.receiptClose?.nativeElement.focus());this.message.set('Receipt delivery retry requested.');},error:e=>this.message.set(e?.error?.message||e?.error?.error||'Receipt delivery could not be retried.')});}
}
