import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DatePipe, DecimalPipe } from '@angular/common';
import { interval, Subscription } from 'rxjs';
import { EventsService } from '../../core/services/events.service';
import { BookingsService } from '../../core/services/bookings.service';
import { AuthService } from '../../core/services/auth.service';
import { RealtimeService, SeatAvailabilityChange } from '../../core/services/realtime.service';
import { EventDto, PublishedSeat, PublishedSeatingLayout, SeatViewAsset } from '../../core/models/api.models';
import { PageStateComponent } from '../../shared/components/page-state.component';
import { SeatViewModalComponent } from '../../shared/components/seat-view-modal.component';
@Component({selector:'app-seat-selection-page',standalone:true,imports:[DatePipe,DecimalPipe,PageStateComponent,SeatViewModalComponent],template:`
<div class="nv-page">
@if(loading()){<div class="nv-skeleton h-[70vh]"></div>}
@else if(error()||!layout()){<app-page-state kind="error" title="Seat layout unavailable" message="This event does not have an available published seating layout right now." actionLabel="Back to Event" [action]="goBack"/>}
@else{
<div class="mb-5"><p class="text-sm font-extrabold nv-muted">Seat selection</p><h1 class="nv-page-title">{{event()?.title||'Choose your seats'}}</h1><p class="nv-muted mt-1">{{event()?.startAtUtc|date:'EEE, MMM d · h:mm a'}}</p></div>
@if(message()){
<div class="mb-5 nv-card px-4 py-3 flex items-start gap-3" [style.borderColor]="messageError()?'color-mix(in srgb,var(--danger) 40%,var(--border))':'color-mix(in srgb,var(--success) 38%,var(--border))'" role="status" aria-live="polite">
  <span class="w-8 h-8 rounded-xl grid place-items-center shrink-0 font-black" [style.background]="messageError()?'color-mix(in srgb,var(--danger) 12%,var(--surface))':'color-mix(in srgb,var(--success) 12%,var(--surface))'" [style.color]="messageError()?'var(--danger)':'var(--success)'">{{messageError()?'!':'✓'}}</span>
  <div class="min-w-0 flex-1"><p class="font-extrabold text-sm">{{messageError()?'Please check your selection':'Seats updated'}}</p><p class="text-sm nv-muted mt-0.5">{{message()}}</p></div>
  <button type="button" class="w-8 h-8 rounded-lg nv-muted hover:bg-[var(--surface-2)]" (click)="dismissMessage()" aria-label="Dismiss message">×</button>
</div>}
<div class="grid xl:grid-cols-[1fr_360px] gap-5">
<section class="nv-card p-4 sm:p-5 overflow-hidden">
<div class="flex flex-wrap items-center justify-between gap-3 mb-4"><div class="flex gap-2 overflow-auto">@for(s of layout()!.sections;track s.id){<button type="button" class="nv-chip whitespace-nowrap" [class.active]="section()===''||section()===s.id" (click)="section.set(section()===s.id?'':s.id)">{{s.name}}</button>}</div><button type="button" class="nv-btn nv-btn-secondary text-sm" (click)="section.set('')">Reset View</button></div>
<div class="overflow-auto rounded-2xl p-2 sm:p-4" style="background:var(--surface-2)"><div class="relative min-w-[720px] min-h-[520px] mx-auto" [style.width.px]="canvasW" [style.height.px]="canvasH">
<div class="absolute rounded-xl flex items-center justify-center text-xs font-black tracking-[.25em]" [style.left.%]="pct(layout()!.stageX,layout()!.canvasWidth)" [style.top.%]="pct(layout()!.stageY,layout()!.canvasHeight)" [style.width.%]="pct(layout()!.stageWidth,layout()!.canvasWidth)" [style.height.%]="pct(layout()!.stageHeight,layout()!.canvasHeight)" style="background:linear-gradient(135deg,#665A88,#9E6987);color:white">STAGE</div>
@for(seat of visibleSeats;track seat.seatId){<button type="button" class="absolute w-7 h-7 rounded-[9px] text-[9px] font-black border transition-transform hover:scale-110 disabled:hover:scale-100" [disabled]="!selectable(seat)" [class.ring-2]="selectedIds().includes(seat.seatId)" [style.left.%]="pct(seat.x,layout()!.canvasWidth)" [style.top.%]="pct(seat.y,layout()!.canvasHeight)" [style.background]="seatColor(seat)" [style.borderColor]="selectedIds().includes(seat.seatId)?'var(--focus)':'color-mix(in srgb,var(--text-2) 35%,transparent)'" [style.borderStyle]="seatBorderStyle(seat)" [style.opacity]="seatOpacity(seat)" [attr.title]="seatAria(seat)" [style.color]="selectedIds().includes(seat.seatId)?'#0F1738':'var(--text)'" [attr.aria-label]="seatAria(seat)" [attr.aria-pressed]="selectedIds().includes(seat.seatId)" (click)="toggleSeat(seat)">{{seat.seatNumber}}</button>}
</div></div>
<div class="flex flex-wrap gap-3 mt-4 text-xs nv-muted"><span class="flex items-center gap-2"><i class="w-3 h-3 rounded" style="background:#7C89A5"></i>Available</span><span class="flex items-center gap-2"><i class="w-3 h-3 rounded" style="background:#80D5CA"></i>Selected</span><span class="flex items-center gap-2"><i class="w-3 h-3 rounded" style="background:#DCAAA8"></i>Held</span><span class="flex items-center gap-2"><i class="w-3 h-3 rounded" style="background:#444E6D"></i>Booked</span></div>
</section>
<aside><div class="nv-card p-5 xl:sticky xl:top-5"><div class="flex justify-between items-center"><h2 class="font-black text-xl">Booking Summary</h2>@if(holdExpires()){<span class="nv-status" style="color:var(--warning)">{{holdTime}}</span>}</div>
@if(selectedSeats.length){<div class="space-y-2 mt-4 max-h-64 overflow-auto">@for(s of selectedSeats;track s.seatId){<div class="nv-card-soft p-3 flex justify-between items-center gap-3"><div><div class="font-extrabold">{{s.categoryName||'Seat'}} · {{s.rowLabel}} {{s.seatNumber}}</div><div class="text-xs nv-muted">{{s.isAccessible?'Accessible seat':'Standard access'}}</div></div><div class="text-right"><strong>LKR {{s.price||0|number:'1.0-2'}}</strong><button type="button" class="block ml-auto text-xs mt-1" (click)="preview(s)">Seat View</button></div></div>}</div><div class="border-t mt-4 pt-4" style="border-color:var(--border)"><div class="flex justify-between"><span class="nv-muted">{{selectedSeats.length}} seat{{selectedSeats.length===1?'':'s'}}</span><strong>LKR {{total|number:'1.0-2'}}</strong></div></div><button type="button" class="nv-btn nv-btn-primary w-full mt-5" [disabled]="busy()" (click)="continue()">{{busy()?'Securing seats...':'Continue to Booking'}}</button>}
@else{<div class="py-10 text-center"><div class="text-3xl opacity-60">▦</div><p class="font-extrabold mt-3">No seats selected</p><p class="nv-muted text-sm mt-1">Choose available seats from the map.</p></div>}
</div></aside></div>}
@if(previewAsset()){<app-seat-view-modal [asset]="previewAsset()!" (closed)="previewAsset.set(null)"/>}
</div>`})
export class SeatSelectionPageComponent implements OnInit,OnDestroy{
  private route=inject(ActivatedRoute); private router=inject(Router); private events=inject(EventsService); private bookings=inject(BookingsService); private auth=inject(AuthService); private realtime=inject(RealtimeService);
  readonly maxSeatsPerHold=10; // mirrors the current backend SeatService limit; the server remains authoritative.
  eventId=''; event=signal<EventDto|null>(null); layout=signal<PublishedSeatingLayout|null>(null); loading=signal(true); error=signal(false); selectedIds=signal<string[]>([]); section=signal(''); busy=signal(false); message=signal(''); messageError=signal(false); holdToken=signal(''); holdExpires=signal<Date|null>(null); previewAsset=signal<SeatViewAsset|null>(null); private timer?:Subscription; canvasW=900;canvasH=560;
  goBack=()=>void this.router.navigate(['/app/events',this.eventId]);
  ngOnInit(){this.eventId=this.route.snapshot.paramMap.get('id')!;this.events.get(this.eventId).subscribe({next:e=>this.event.set(e),error:()=>void 0});this.events.layout(this.eventId).subscribe({next:l=>{this.layout.set(l);this.loading.set(false);if(this.auth.isAuthenticated())void this.realtime.joinEvent(this.eventId,c=>this.applyRealtimeSeatChange(c));},error:()=>{this.error.set(true);this.loading.set(false);}});this.timer=interval(1000).subscribe(()=>{if(this.holdExpires()&&this.holdExpires()!.getTime()<=Date.now()){this.holdExpires.set(null);this.holdToken.set('');this.messageError.set(true);this.message.set('Your seat hold expired. Please select the seats again.');this.refreshLayout();}});}
  ngOnDestroy(){this.timer?.unsubscribe();void this.realtime.leaveEvent(this.eventId);if(this.holdToken())this.events.releaseHold(this.holdToken()).subscribe({error:()=>void 0});}
  get visibleSeats(){const l=this.layout();if(!l)return[];return this.section()?l.seats.filter(s=>s.sectionId===this.section()):l.seats;}
  get selectedSeats(){const ids=this.selectedIds();return this.layout()?.seats.filter(s=>ids.includes(s.seatId))??[];}
  get total(){return this.selectedSeats.reduce((a,s)=>a+(s.price??0),0);}
  get holdTime(){if(!this.holdExpires())return'';const s=Math.max(0,Math.floor((this.holdExpires()!.getTime()-Date.now())/1000));return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`;}
  pct(v:number,total:number){return total?Math.max(0,Math.min(96,(v/total)*100)):0;} selectable(s:PublishedSeat){return /available/i.test(s.state);} seatColor(s:PublishedSeat){if(this.selectedIds().includes(s.seatId))return'#80D5CA';if(/held/i.test(s.state))return'#DCAAA8';if(/booked|blocked|unavailable/i.test(s.state))return'#444E6D';return'#7C89A5';} seatBorderStyle(s:PublishedSeat){if(/held/i.test(s.state))return'dashed';if(/booked|blocked|unavailable/i.test(s.state))return'double';return'solid';} seatOpacity(s:PublishedSeat){return /booked|blocked|unavailable/i.test(s.state)?0.62:1;} seatAria(s:PublishedSeat){return `${s.categoryName||'Seat'}, row ${s.rowLabel}, seat ${s.seatNumber}, ${s.price??0} LKR, ${s.state}${s.isAccessible?', accessible':''}`;}
  toggleSeat(s:PublishedSeat){if(!this.selectable(s))return;this.dismissMessage();const ids=this.selectedIds();if(ids.includes(s.seatId))this.selectedIds.set(ids.filter(x=>x!==s.seatId));else if(ids.length<this.maxSeatsPerHold)this.selectedIds.set([...ids,s.seatId]);else{this.messageError.set(true);this.message.set(`You can select up to ${this.maxSeatsPerHold} seats in one booking.`);}}
  preview(s:PublishedSeat){this.events.seatView(this.eventId,s.seatId).subscribe({next:v=>this.previewAsset.set(v),error:()=>{this.messageError.set(true);this.message.set('Seat view preview is not available for this seat.');}});}
  dismissMessage(){this.message.set('');this.messageError.set(false);}
  continue(){if(!this.selectedIds().length)return;if(!this.auth.isAuthenticated()){void this.router.navigate(['/auth/sign-in'],{queryParams:{returnUrl:this.router.url}});return;}const seatIds=[...this.selectedIds()];this.busy.set(true);this.dismissMessage();this.events.holdSeats(this.eventId,seatIds,this.holdToken()||undefined).subscribe({next:r=>{if(!r.succeeded||!r.hold){this.busy.set(false);this.messageError.set(true);this.message.set(this.safeMessage(r.message,'Those seats could not be reserved just now. The map has been refreshed — please choose the seats again.'));this.refreshLayout();return;}this.holdToken.set(r.hold.holdToken);this.holdExpires.set(new Date(r.hold.expiresAtUtc));this.bookings.create(this.eventId,r.hold.holdToken,seatIds).subscribe({next:b=>{this.holdToken.set('');this.busy.set(false);void this.router.navigate(['/app/payments',b.bookingId]);},error:e=>{const token=this.holdToken();this.holdToken.set('');this.holdExpires.set(null);if(token)this.events.releaseHold(token).subscribe({error:()=>void 0});this.busy.set(false);this.messageError.set(true);this.message.set(this.safeApiMessage(e,"We couldn't create the booking. No payment was made and the temporary seat hold was released. Please try again."));this.refreshLayout();}});},error:e=>{this.busy.set(false);this.messageError.set(true);this.message.set(this.safeApiMessage(e,"We couldn't reserve those seats just now. The map has been refreshed — please choose the seats again."));this.refreshLayout();}});}
  private safeApiMessage(error:unknown,fallback:string){const envelope=error&&typeof error==='object'?error as Record<string,unknown>:null;const payload=envelope?.['error'];let candidate='';if(typeof payload==='string')candidate=payload;else if(payload&&typeof payload==='object'){const body=payload as Record<string,unknown>;if(typeof body['message']==='string')candidate=body['message'];else if(typeof body['title']==='string')candidate=body['title'];}return this.safeMessage(candidate,fallback);}
  private safeMessage(candidate:unknown,fallback:string){const value=typeof candidate==='string'?candidate.trim():'';if(!value||/unexpected server error|internal server error|an error occurred|something went wrong/i.test(value))return fallback;return value;}
  private applyRealtimeSeatChange(change:SeatAvailabilityChange){if(String(change.eventId).toLowerCase()!==this.eventId.toLowerCase())return;const changed=new Set(change.seatIds.map(x=>String(x).toLowerCase()));this.layout.update(current=>current?{...current,seats:current.seats.map(s=>changed.has(s.seatId.toLowerCase())?{...s,state:change.state,heldUntilUtc:change.expiresAtUtc??null}:s)}:current);if(!this.busy()&&!/available/i.test(change.state)){const removed=this.selectedIds().filter(id=>changed.has(id.toLowerCase()));if(removed.length){this.selectedIds.update(ids=>ids.filter(id=>!changed.has(id.toLowerCase())));this.messageError.set(true);this.message.set('A selected seat just became unavailable. Please choose another seat.');}}}
  private refreshLayout(){this.events.layout(this.eventId).subscribe({next:l=>{this.layout.set(l);this.selectedIds.set([]);},error:()=>void 0});}
}
