import { Component, OnInit, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DecimalPipe } from '@angular/common';
import { forkJoin, of, catchError } from 'rxjs';
import { EventsService } from '../../core/services/events.service';
import { VenuesService } from '../../core/services/venues.service';
import { ReportsService } from '../../core/services/reports.service';
import { EventDto, OrganizerReportDto, VenueRentalDto } from '../../core/models/api.models';
@Component({selector:'app-organizer-dashboard',standalone:true,imports:[RouterLink,DecimalPipe],template:`
<div class="nv-page space-y-6"><section class="nv-hero min-h-[210px]"><div class="relative z-10"><p class="font-extrabold text-sm opacity-75">Organizer workspace</p><h1 class="nv-page-title mt-1">Organizer Dashboard</h1><p class="mt-2 opacity-80 max-w-2xl">Create, publish and operate events from one workspace.</p><a routerLink="/organizer/host-event" class="nv-btn nv-btn-primary mt-6">Host Event</a></div></section>
<div class="grid grid-cols-2 xl:grid-cols-4 gap-4">@for(k of kpis;track k.label){<div class="nv-card p-5"><div class="text-sm nv-muted">{{k.label}}</div><div class="text-3xl font-black mt-2">{{k.money?'LKR ':''}}{{k.value|number:'1.0-2'}}</div></div>}</div>
<div class="grid xl:grid-cols-[1fr_360px] gap-5"><section class="nv-card p-5"><div class="flex justify-between items-center gap-3"><div><h2 class="text-xl font-black">My events</h2><p class="nv-muted text-sm">Recent drafts and published events.</p></div><a routerLink="/organizer/events" class="nv-btn nv-btn-secondary">View All</a></div><div class="space-y-3 mt-4">@for(e of events().slice(0,5);track e.eventId){<div class="nv-card-soft p-4 flex flex-col sm:flex-row sm:items-center gap-3"><div class="flex-1"><div class="font-extrabold">{{e.title}}</div><div class="text-sm nv-muted mt-1">{{status(e.status)}} · {{e.category}}</div></div><div class="flex gap-2"><a [routerLink]="['/organizer/events',e.eventId,'edit']" class="nv-btn nv-btn-secondary">Edit</a><a routerLink="/organizer/seating" [queryParams]="{event:e.eventId}" class="nv-btn nv-btn-secondary">Seating</a></div></div>}@empty{<div class="py-10 text-center nv-muted">No events created yet.</div>}</div></section><aside class="space-y-4"><section class="nv-card p-5"><h2 class="font-black">Venue rentals</h2><div class="mt-4 space-y-2">@for(r of rentals().slice(0,4);track r.rentalRequestId){<div class="nv-card-soft p-3"><div class="font-extrabold text-sm">{{r.purpose}}</div><div class="text-xs nv-muted mt-1">Status {{rentalStatus(r.status)}}</div></div>}@empty{<p class="nv-muted text-sm">No venue rental requests yet.</p>}</div></section><section class="nv-card p-5"><h2 class="font-black">Quick actions</h2><div class="grid gap-2 mt-4"><a routerLink="/organizer/host-event" class="nv-card-soft p-3 font-extrabold">Create event</a><a routerLink="/organizer/check-in" class="nv-card-soft p-3 font-extrabold">Open check-in</a><a routerLink="/organizer/orders" class="nv-card-soft p-3 font-extrabold">Manage food orders</a><a routerLink="/organizer/analytics" class="nv-card-soft p-3 font-extrabold">View analytics</a></div></section></aside></div></div>`})
export class OrganizerDashboardComponent implements OnInit{private eventsApi=inject(EventsService);private venues=inject(VenuesService);private reports=inject(ReportsService);events=signal<EventDto[]>([]);rentals=signal<VenueRentalDto[]>([]);report=signal<OrganizerReportDto|null>(null);get kpis(){const r=this.report();return[{label:'Events',value:r?.events??this.events().length},{label:'Published',value:r?.publishedEvents??this.events().filter(e=>e.status===1).length},{label:'Confirmed bookings',value:r?.confirmedBookings??0},{label:'Revenue',value:r?.revenue??0,money:true}];}ngOnInit(){forkJoin({events:this.eventsApi.mine().pipe(catchError(()=>of([]))),rentals:this.venues.rentalsMine().pipe(catchError(()=>of([]))),report:this.reports.organizer().pipe(catchError(()=>of(null))) }).subscribe(v=>{this.events.set(v.events);this.rentals.set(v.rentals);this.report.set(v.report);});}status(v:number){return ['Draft','Published','Cancelled','Completed'][v]??'Unknown';}rentalStatus(v:number){return ['Pending','Accepted','Rejected','Negotiating','Cancelled'][v]??String(v);}}
