import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Observable } from 'rxjs';
import { AuthService } from '../../core/services/auth.service';
import { USER_ROLE, UserRole } from '../../core/models/api.models';

@Component({selector:'app-auth-page',standalone:true,imports:[FormsModule,RouterLink],template:`
<main id="main-content" tabindex="-1" class="nv-auth-shell min-h-screen grid lg:grid-cols-[1.1fr_.9fr] bg-[var(--bg)]" [class.nv-auth-shell--login]="mode==='sign-in'">
  @if(mode!=='sign-in'){
  <section class="relative hidden lg:flex p-10 overflow-hidden items-end" style="background-image:linear-gradient(135deg,rgba(15,23,56,.52),rgba(15,23,56,.22)),url('/assets/nvent/images/auth/auth-background.webp');background-size:cover;background-position:center">
    <div class="absolute inset-0 opacity-35" style="background:radial-gradient(circle at 20% 18%,white,transparent 28%),radial-gradient(circle at 78% 64%,white,transparent 20%),linear-gradient(180deg,transparent 58%,rgba(52,71,110,.25))"></div>
    <div class="relative max-w-xl text-white pb-10"><div class="flex items-center gap-3 mb-6"><img src="assets/brand/nvent-mark.svg" class="w-12 h-12" alt=""><span class="text-2xl font-black">Nvent</span></div><h1 class="text-5xl font-black tracking-[-.05em] leading-[1.02]">Access your Nvent account.</h1><p class="mt-5 text-white/85 text-lg">Manage events, bookings, tickets, parking, food and account services after signing in.</p></div>
  </section>
  } @else {
    <a routerLink="/app/home" class="nv-login-brand" aria-label="Nvent home"><span class="nv-login-brand-mark"><img src="assets/brand/nvent-mark.svg" alt=""></span><span>Nvent</span></a>
    <div class="nv-login-story hidden lg:block" aria-hidden="true"><span class="nv-login-story-kicker">NVent experience</span><h1>One place.<br>Every unforgettable event.</h1><p>Discover, book and manage the moments worth showing up for.</p></div>
  }
  <section class="nv-auth-content flex items-center justify-center p-5 sm:p-8" [class.nv-auth-content--login]="mode==='sign-in'"><div class="w-full max-w-[520px]" [class.nv-auth-card-wrap]="mode==='sign-in'">
    @if(mode!=='sign-in'){<a routerLink="/app/home" class="flex items-center gap-2 font-black text-xl mb-8 lg:hidden"><img src="assets/brand/nvent-mark.svg" class="w-9 h-9" alt="">Nvent</a>}
    <div class="nv-card nv-glass-panel p-6 sm:p-8" [class.nv-login-card]="mode==='sign-in'">
      @if(mode==='sign-in'){
        <div class="nv-login-card-head">
          <div><span class="nv-login-eyebrow"><span></span> Welcome back</span><h2>Sign in to <span>Nvent</span></h2><p>Your events, tickets and experiences are waiting.</p></div>
          <div class="nv-login-lock" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="10" width="14" height="10" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v2"/></svg></div>
        </div>
        <form (ngSubmit)="signIn()" class="space-y-5 nv-login-form">
          <div><label class="nv-label">Email address</label><div class="nv-login-field"><span class="nv-login-field-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4.5 7 7.5 6 7.5-6"/></svg></span><input class="nv-input nv-login-input" type="email" name="email" [(ngModel)]="email" autocomplete="email" placeholder="you@example.com" required aria-label="Email"></div></div>
          <div><label class="nv-label">Password</label><div class="relative nv-login-field nv-login-field--password"><span class="nv-login-field-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg></span><input class="nv-input nv-login-input" [type]="passwordVisible?'text':'password'" name="password" [(ngModel)]="password" autocomplete="current-password" placeholder="Enter your password" required aria-label="Password"><button type="button" class="nv-login-eye absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 grid place-items-center rounded-xl" (click)="passwordVisible=!passwordVisible" [attr.aria-label]="passwordVisible?'Hide password':'Show password'" [attr.title]="passwordVisible?'Hide password':'Show password'" [attr.aria-pressed]="passwordVisible"><svg aria-hidden="true" viewBox="0 0 24 24" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">@if(passwordVisible){<path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5 0 8.5 4.5 9.5 6a2 2 0 0 1 0 2 15.7 15.7 0 0 1-2.4 2.9"/><path d="M6.6 6.6A16.2 16.2 0 0 0 2.5 10a2 2 0 0 0 0 2c1 1.5 4.5 6 9.5 6 1 0 2-.2 2.9-.5"/>}@else{<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6S2.5 12 2.5 12z"/><circle cx="12" cy="12" r="2.5"/>}</svg></button></div><div class="nv-login-forgot-row"><a routerLink="/auth/forgot-password" class="nv-login-link text-sm font-bold">Forgot password?</a></div></div>
          <button type="submit" class="nv-login-submit w-full" [disabled]="busy()"><span>{{busy()?'Signing in...':'Sign In'}}</span>@if(!busy()){<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg>}</button>
        </form>
        <div class="nv-login-divider"><span>New here?</span></div>
        <a routerLink="/auth/sign-up" class="nv-login-create">Create your Nvent account <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a>
      } @else if(mode==='sign-up'){
        <p class="text-sm font-extrabold nv-muted">Create account</p><h2 class="nv-page-title mt-1">Join Nvent</h2><p class="nv-muted mt-2 mb-6">Choose your account type and enter your details.</p>
        <form (ngSubmit)="signUp()" class="space-y-4"><div class="grid sm:grid-cols-2 gap-3"><div><label class="nv-label">First name</label><input class="nv-input" name="first" [(ngModel)]="firstName" required aria-label="First name"></div><div><label class="nv-label">Last name</label><input class="nv-input" name="last" [(ngModel)]="lastName" required aria-label="Last name"></div></div><div><label class="nv-label">Email</label><input class="nv-input" type="email" name="email" [(ngModel)]="email" required aria-label="Email"></div><div><label class="nv-label">Phone</label><input class="nv-input" name="phone" [(ngModel)]="phoneNumber" aria-label="Phone"></div><div><label class="nv-label">Account type</label><select class="nv-input" name="role" [(ngModel)]="role" aria-label="Account type"><option [ngValue]="0">Customer</option><option [ngValue]="1">Event Organizer</option><option [ngValue]="2">Venue Owner</option></select></div><div><label class="nv-label">Password</label><div class="relative"><input class="nv-input pr-12" [type]="passwordVisible?'text':'password'" name="password" [(ngModel)]="password" minlength="8" autocomplete="new-password" required aria-label="Password"><button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 grid place-items-center rounded-lg nv-muted hover:text-[var(--text)] focus-visible:outline-2 focus-visible:outline-offset-2" (click)="passwordVisible=!passwordVisible" [attr.aria-label]="passwordVisible?'Hide password':'Show password'" [attr.title]="passwordVisible?'Hide password':'Show password'" [attr.aria-pressed]="passwordVisible"><svg aria-hidden="true" viewBox="0 0 24 24" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">@if(passwordVisible){<path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5 0 8.5 4.5 9.5 6a2 2 0 0 1 0 2 15.7 15.7 0 0 1-2.4 2.9"/><path d="M6.6 6.6A16.2 16.2 0 0 0 2.5 10a2 2 0 0 0 0 2c1 1.5 4.5 6 9.5 6 1 0 2-.2 2.9-.5"/>}@else{<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6S2.5 12 2.5 12z"/><circle cx="12" cy="12" r="2.5"/>}</svg></button></div></div><button type="submit" class="nv-btn nv-btn-primary w-full" [disabled]="busy()">{{busy()?'Creating...':'Create Account'}}</button></form><p class="text-center text-sm nv-muted mt-5">Already have an account? <a routerLink="/auth/sign-in" class="font-extrabold text-[var(--primary)]">Sign in</a></p>
      } @else if(mode==='verify'){
        <p class="text-sm font-extrabold nv-muted">Email verification</p><h2 class="nv-page-title mt-1">Verify your email</h2><p class="nv-muted mt-2 mb-6">Enter the OTP sent to {{email||'your email'}}.</p><form (ngSubmit)="verify()" class="space-y-4"><div><label class="nv-label">Email</label><input class="nv-input" type="email" name="email" [(ngModel)]="email" required aria-label="Email"></div><div><label class="nv-label">OTP</label><input class="nv-input tracking-[.35em] text-center text-xl" name="otp" [(ngModel)]="otp" maxlength="8" inputmode="numeric" required aria-label="OTP"></div><button type="submit" class="nv-btn nv-btn-primary w-full" [disabled]="busy()">{{busy()?'Verifying...':'Verify Email'}}</button><button type="button" class="nv-btn nv-btn-secondary w-full" (click)="resend()">Resend OTP</button></form>
      } @else if(mode==='forgot'){
        <p class="text-sm font-extrabold nv-muted">Account recovery</p><h2 class="nv-page-title mt-1">Forgot password</h2><p class="nv-muted mt-2 mb-6">Enter your email and we’ll send you a secure password-reset link.</p><form (ngSubmit)="forgot()" class="space-y-4"><div><label class="nv-label">Email</label><input class="nv-input" type="email" name="email" [(ngModel)]="email" required aria-label="Email"></div><button type="submit" class="nv-btn nv-btn-primary w-full" [disabled]="busy()">{{busy()?'Sending...':'Send Reset Request'}}</button></form><a routerLink="/auth/sign-in" class="nv-btn nv-btn-secondary w-full mt-3">Back to Sign In</a>
      } @else {
        <p class="text-sm font-extrabold nv-muted">Password reset</p><h2 class="nv-page-title mt-1">Create a new password</h2><p class="nv-muted mt-2 mb-6">Choose a new password for your Nvent account.</p><form (ngSubmit)="reset()" class="space-y-4">@if(!token){<div><label class="nv-label">Reset token</label><input class="nv-input" name="token" [(ngModel)]="token" required aria-label="Reset token"></div>}@else{<div class="rounded-xl border p-3 text-sm nv-muted" style="border-color:var(--border);background:color-mix(in srgb,var(--success) 8%,var(--surface))">Secure reset link loaded from your email.</div>}<div><label class="nv-label">New password</label><div class="relative"><input class="nv-input pr-12" [type]="passwordVisible?'text':'password'" name="password" [(ngModel)]="password" minlength="8" autocomplete="new-password" required aria-label="New password"><button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 grid place-items-center rounded-lg nv-muted hover:text-[var(--text)] focus-visible:outline-2 focus-visible:outline-offset-2" (click)="passwordVisible=!passwordVisible" [attr.aria-label]="passwordVisible?'Hide password':'Show password'" [attr.title]="passwordVisible?'Hide password':'Show password'" [attr.aria-pressed]="passwordVisible"><svg aria-hidden="true" viewBox="0 0 24 24" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">@if(passwordVisible){<path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5 0 8.5 4.5 9.5 6a2 2 0 0 1 0 2 15.7 15.7 0 0 1-2.4 2.9"/><path d="M6.6 6.6A16.2 16.2 0 0 0 2.5 10a2 2 0 0 0 0 2c1 1.5 4.5 6 9.5 6 1 0 2-.2 2.9-.5"/>}@else{<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6S2.5 12 2.5 12z"/><circle cx="12" cy="12" r="2.5"/>}</svg></button></div></div><button type="submit" class="nv-btn nv-btn-primary w-full" [disabled]="busy()">{{busy()?'Resetting...':'Reset Password'}}</button></form>
      }
      @if(message()){<div class="mt-4 p-3 rounded-xl text-sm" [style.background]="error()?'color-mix(in srgb,var(--danger) 12%,var(--surface))':'color-mix(in srgb,var(--success) 12%,var(--surface))'" [style.color]="error()?'var(--danger)':'var(--success)'" role="status">{{message()}}</div>}
    </div>
  </div></section>
</main>`,styles:[`
:host{display:block}
.nv-auth-shell--login{position:relative;display:flex!important;min-height:100svh;overflow:hidden;background-image:url('/assets/nvent/images/auth/auth-background.webp');background-size:cover;background-position:center 54%;isolation:isolate}
.nv-auth-shell--login::before{content:'';position:absolute;inset:0;z-index:0;background:linear-gradient(90deg,rgba(4,11,30,.78) 0%,rgba(4,13,34,.38) 43%,rgba(4,11,30,.24) 62%,rgba(4,11,30,.58) 100%)}
.nv-auth-shell--login::after{content:'';position:absolute;inset:0;z-index:0;background:radial-gradient(circle at 78% 50%,rgba(113,214,226,.17),transparent 27%),radial-gradient(circle at 21% 84%,rgba(255,176,158,.16),transparent 28%),linear-gradient(180deg,rgba(3,8,24,.04),rgba(3,8,24,.34))}
.nv-login-brand{position:absolute;z-index:3;top:clamp(1.35rem,3vw,2.5rem);left:clamp(1.35rem,4vw,4.5rem);display:flex;align-items:center;gap:.8rem;color:white;font-size:1.35rem;font-weight:900;letter-spacing:-.03em;text-decoration:none;text-shadow:0 2px 18px rgba(0,0,0,.24)}
.nv-login-brand-mark{width:2.7rem;height:2.7rem;display:grid;place-items:center;border-radius:1rem;background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.23);backdrop-filter:blur(16px);box-shadow:0 12px 32px rgba(0,0,0,.16)}
.nv-login-brand-mark img{width:2rem;height:2rem}
.nv-login-story{position:absolute;z-index:2;left:clamp(2rem,5vw,5.5rem);bottom:clamp(2.5rem,7vh,6rem);max-width:36rem;color:white;text-shadow:0 4px 24px rgba(0,0,0,.32)}
.nv-login-story-kicker{display:inline-flex;align-items:center;padding:.48rem .8rem;border:1px solid rgba(255,255,255,.24);border-radius:999px;background:rgba(255,255,255,.10);backdrop-filter:blur(10px);font-size:.73rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase}
.nv-login-story h1{margin:1.1rem 0 .8rem;font-size:clamp(2.8rem,4.6vw,5rem);line-height:.94;font-weight:950;letter-spacing:-.065em;max-width:13ch}
.nv-login-story p{max-width:32rem;font-size:clamp(1rem,1.35vw,1.22rem);line-height:1.65;color:rgba(255,255,255,.82)}
.nv-auth-content--login{position:relative;z-index:2;width:100%;min-height:100svh;justify-content:center!important;padding:6rem 1.25rem 2rem!important}
.nv-auth-card-wrap{max-width:31rem!important;width:100%}
.nv-login-card{position:relative;overflow:hidden;border-radius:2rem!important;padding:clamp(1.5rem,3vw,2.25rem)!important;background:linear-gradient(145deg,rgba(13,27,61,.67),rgba(8,18,45,.48))!important;border:1px solid rgba(255,255,255,.22)!important;box-shadow:0 34px 90px rgba(0,0,0,.36),inset 0 1px 0 rgba(255,255,255,.14)!important;backdrop-filter:blur(28px) saturate(145%);-webkit-backdrop-filter:blur(28px) saturate(145%);color:white}
.nv-login-card::before{content:'';position:absolute;inset:-1px;pointer-events:none;border-radius:inherit;background:linear-gradient(120deg,rgba(255,255,255,.22),transparent 24%,transparent 72%,rgba(111,216,228,.13));mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask-composite:exclude;padding:1px}
.nv-login-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;margin-bottom:2rem}
.nv-login-eyebrow{display:inline-flex;align-items:center;gap:.5rem;color:rgba(255,255,255,.68);font-size:.73rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}
.nv-login-eyebrow span{width:.48rem;height:.48rem;border-radius:999px;background:#72d5e1;box-shadow:0 0 0 5px rgba(114,213,225,.12),0 0 18px rgba(114,213,225,.7)}
.nv-login-card-head h2{margin:.55rem 0 .45rem;font-size:clamp(2rem,4vw,2.75rem);line-height:1;font-weight:950;letter-spacing:-.055em;color:#fff}
.nv-login-card-head h2 span{background:linear-gradient(90deg,#8de2ea,#ffd0c6);-webkit-background-clip:text;background-clip:text;color:transparent}
.nv-login-card-head p{margin:0;color:rgba(255,255,255,.68);line-height:1.6}
.nv-login-lock{flex:0 0 auto;width:3rem;height:3rem;display:grid;place-items:center;border-radius:1rem;color:#b7eff3;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.14);box-shadow:inset 0 1px 0 rgba(255,255,255,.08)}
.nv-login-lock svg{width:1.35rem;height:1.35rem}
.nv-login-card .nv-label{display:block;margin-bottom:.52rem;color:rgba(255,255,255,.87)!important;font-size:.82rem;font-weight:800}
.nv-login-field{position:relative}
.nv-login-field-icon{position:absolute;z-index:2;left:1rem;top:50%;transform:translateY(-50%);width:1.15rem;height:1.15rem;color:rgba(255,255,255,.48);pointer-events:none}
.nv-login-field-icon svg{width:100%;height:100%}
.nv-login-card .nv-input{height:3.35rem;border-radius:1rem!important;border:1px solid rgba(255,255,255,.14)!important;background:rgba(5,14,36,.46)!important;color:white!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important;transition:border-color .2s ease,background .2s ease,box-shadow .2s ease,transform .2s ease}
.nv-login-card .nv-login-input{padding-left:3.15rem!important;padding-right:1.05rem!important}
.nv-login-card .nv-login-field--password .nv-login-input{padding-right:3.75rem!important}
.nv-login-forgot-row{display:flex;justify-content:flex-end;margin-top:.65rem;padding-right:.15rem}
.nv-login-card .nv-input::placeholder{color:rgba(255,255,255,.35)}
.nv-login-card .nv-input:hover{border-color:rgba(255,255,255,.25)!important;background:rgba(5,14,36,.55)!important}
.nv-login-card .nv-input:focus{outline:none;border-color:rgba(121,218,228,.92)!important;background:rgba(5,14,36,.65)!important;box-shadow:0 0 0 4px rgba(121,218,228,.13),0 12px 30px rgba(0,0,0,.12)!important}
.nv-login-link{color:#a9e7ed!important;text-decoration:none;transition:color .2s ease,text-shadow .2s ease}
.nv-login-link:hover{color:white!important;text-shadow:0 0 18px rgba(129,221,231,.5)}
.nv-login-eye{color:rgba(255,255,255,.54);background:transparent;border:0;transition:color .2s ease,background .2s ease}
.nv-login-eye:hover,.nv-login-eye:focus-visible{color:white;background:rgba(255,255,255,.09);outline:none}
.nv-login-submit{height:3.45rem;display:flex;align-items:center;justify-content:center;gap:.7rem;border:0;border-radius:1rem;color:#07152d;font-weight:950;letter-spacing:-.01em;background:linear-gradient(100deg,#72d5e1 0%,#a9d5de 48%,#f4c4bd 100%);box-shadow:0 16px 38px rgba(77,184,201,.24),inset 0 1px 0 rgba(255,255,255,.65);transition:transform .2s ease,box-shadow .2s ease,filter .2s ease}
.nv-login-submit svg,.nv-login-create svg{width:1.15rem;height:1.15rem;transition:transform .2s ease}
.nv-login-submit:hover:not(:disabled){transform:translateY(-2px);box-shadow:0 20px 44px rgba(77,184,201,.34),inset 0 1px 0 rgba(255,255,255,.7);filter:saturate(1.06)}
.nv-login-submit:hover:not(:disabled) svg,.nv-login-create:hover svg{transform:translateX(3px)}
.nv-login-submit:disabled{opacity:.65;cursor:not-allowed}
.nv-login-divider{display:flex;align-items:center;gap:.9rem;margin:1.5rem 0 .9rem;color:rgba(255,255,255,.4);font-size:.75rem;font-weight:800;text-transform:uppercase;letter-spacing:.09em}
.nv-login-divider::before,.nv-login-divider::after{content:'';height:1px;flex:1;background:linear-gradient(90deg,transparent,rgba(255,255,255,.15))}.nv-login-divider::after{transform:scaleX(-1)}
.nv-login-create{display:flex;align-items:center;justify-content:center;gap:.55rem;min-height:3rem;border-radius:1rem;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.055);color:rgba(255,255,255,.88)!important;font-size:.88rem;font-weight:800;text-decoration:none;transition:background .2s ease,border-color .2s ease,transform .2s ease}
.nv-login-create:hover{background:rgba(255,255,255,.10);border-color:rgba(255,255,255,.24);transform:translateY(-1px)}
@media (min-width:1024px){.nv-auth-content--login{justify-content:flex-end!important;padding:4.5rem clamp(3rem,7vw,8rem) 3rem!important}.nv-auth-card-wrap{max-width:30rem!important}}
@media (max-width:767px){.nv-auth-shell--login{background-position:61% center}.nv-auth-shell--login::before{background:linear-gradient(180deg,rgba(4,10,28,.44),rgba(4,10,28,.66))}.nv-login-brand{top:1.1rem;left:1.1rem}.nv-login-brand-mark{width:2.35rem;height:2.35rem;border-radius:.8rem}.nv-login-brand-mark img{width:1.7rem;height:1.7rem}.nv-auth-content--login{padding-top:5.8rem!important}.nv-login-card{border-radius:1.55rem!important}.nv-login-lock{display:none}.nv-login-card-head{margin-bottom:1.5rem}}
@media (prefers-reduced-motion:reduce){.nv-login-submit,.nv-login-submit svg,.nv-login-create,.nv-login-create svg{transition:none}}
`]})
export class AuthPageComponent implements OnInit{private route=inject(ActivatedRoute);private router=inject(Router);private auth=inject(AuthService);mode='sign-in';email='';password='';passwordVisible=false;firstName='';lastName='';phoneNumber='';role:UserRole=USER_ROLE.Customer;otp='';token='';busy=signal(false);message=signal('');error=signal(false);ngOnInit(){this.mode=this.route.snapshot.data['mode']??'sign-in';this.email=this.route.snapshot.queryParamMap.get('email')??'';this.token=this.route.snapshot.queryParamMap.get('token')??'';const requestedRole=Number(this.route.snapshot.queryParamMap.get('role'));if([USER_ROLE.Customer,USER_ROLE.EventOrganizer,USER_ROLE.VenueOwner].includes(requestedRole as UserRole))this.role=requestedRole as UserRole;}signIn(){this.run(()=>this.auth.login({email:this.email,password:this.password}),v=>{const returnUrl=this.route.snapshot.queryParamMap.get('returnUrl');void this.router.navigateByUrl(this.auth.postLoginRoute(returnUrl));});}signUp(){this.run(()=>this.auth.register({firstName:this.firstName,lastName:this.lastName,email:this.email,password:this.password,phoneNumber:this.phoneNumber||null,role:this.role}),v=>void this.router.navigate(['/auth/verify-email'],{queryParams:{email:v.email}}));}verify(){this.run(()=>this.auth.verifyEmail(this.email,this.otp),()=>{this.message.set('Email verified. You can sign in now.');setTimeout(()=>void this.router.navigateByUrl('/auth/sign-in'),700);});}resend(){this.run(()=>this.auth.resendOtp(this.email),()=>this.message.set('A new OTP has been sent.'));}forgot(){this.run(()=>this.auth.requestPasswordReset(this.email),()=>this.message.set('If that account exists, reset instructions have been sent.'));}reset(){this.run(()=>this.auth.confirmPasswordReset(this.token,this.password),()=>{this.message.set('Password reset successfully.');setTimeout(()=>void this.router.navigateByUrl('/auth/sign-in'),700);});}private run<T>(fn:()=>Observable<T>,ok:(v:T)=>void){this.busy.set(true);this.error.set(false);this.message.set('');fn().subscribe({next:(v:T)=>{this.busy.set(false);ok(v);},error:(e:unknown)=>{this.busy.set(false);this.error.set(true);this.message.set(this.errorMessage(e));}});}private errorMessage(e:unknown){const value=e as {error?:{message?:string;error?:string}}|null;return value?.error?.message||value?.error?.error||'Something went wrong. Please try again.';}}
