import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { SeatCategoryDto, SeatSectionDto, SeatingLayoutDto } from '../../../core/models/api.models';
import { DomainApiService } from '../../../core/services/domain-api.service';
import { httpErrorMessage } from '../../../core/utils/http-error';

interface StageChoice { label:string; value:number; help:string; }
@Component({selector:'app-seating-builder',imports:[FormsModule],templateUrl:'./seating-builder.html',styleUrl:'./seating-builder.scss'})
export class SeatingBuilderComponent implements OnInit {
 private readonly route=inject(ActivatedRoute); private readonly domain=inject(DomainApiService);
 readonly eventId=this.route.snapshot.queryParamMap.get('eventId')??'';
 readonly stages:StageChoice[]=[{label:'Arena Stage',value:1,help:'Large central performance environment'},{label:'Proscenium Theatre Stage',value:2,help:'Traditional framed theatre stage'},{label:'End-On Stage',value:3,help:'Audience faces one end of the room'},{label:'Thrust Stage',value:4,help:'Stage projects into the audience'},{label:'Traverse Stage',value:5,help:'Audience sits on two opposing sides'},{label:'In-the-Round Stage',value:6,help:'Audience surrounds the performance area'}];
 selectedStage=2;rows=8;columns=12;sectionName='Main Floor';sectionCode='MAIN';categoryName='Standard';categoryCode='STD';categoryPrice=5000;
 readonly layout=signal<SeatingLayoutDto|null>(null);readonly section=signal<SeatSectionDto|null>(null);readonly category=signal<SeatCategoryDto|null>(null);readonly status=signal('Start by configuring the stage');readonly error=signal('');readonly saving=signal(false);readonly generated=signal(0);
 get seatCount():number{return this.safeRows*this.safeColumns;} get safeRows():number{return Math.max(1,Math.min(30,Number(this.rows)||1));} get safeColumns():number{return Math.max(1,Math.min(40,Number(this.columns)||1));}
 get previewColumns():number{return Math.min(this.safeColumns,20);} get rowRange():number[]{return Array.from({length:Math.min(this.safeRows,16)},(_,i)=>i);} get colRange():number[]{return Array.from({length:Math.min(this.safeColumns,20)},(_,i)=>i);} rowLabel(index:number):string{return String.fromCharCode(65+index);} stageLabel():string{return this.stages.find(s=>s.value===this.selectedStage)?.label??'Stage';}
 ngOnInit():void{if(!this.eventId)return;this.domain.organizerLayout(this.eventId).subscribe({next:(layout)=>{this.layout.set(layout);this.selectedStage=Number(layout.stageType)||2;this.rows=layout.rowCount;this.columns=layout.columnCount;this.section.set(layout.sections[0]??null);this.category.set(layout.categories[0]??null);if(layout.sections[0]){this.sectionName=layout.sections[0].name;this.sectionCode=layout.sections[0].code;}if(layout.categories[0]){this.categoryName=layout.categories[0].name;this.categoryCode=layout.categories[0].code;this.categoryPrice=layout.categories[0].price;}this.status.set(layout.isPublished?'Published layout':'Existing draft loaded');},error:()=>{/* first-time configuration returns 404 */}});}
 saveBase():void{if(!this.eventId){this.error.set('Open this builder from a created event so the event ID is available.');return;}this.saving.set(true);this.error.set('');const g=this.geometry();this.domain.saveLayout(this.eventId,{stageType:this.selectedStage,rowCount:this.safeRows,columnCount:this.safeColumns,canvasWidth:900,canvasHeight:620,stageX:g.x,stageY:g.y,stageWidth:g.w,stageHeight:g.h}).subscribe({next:(layout)=>{this.layout.set(layout);this.saving.set(false);this.status.set('Stage configuration saved');},error:(error)=>{this.error.set(httpErrorMessage(error,'The layout could not be saved.'));this.saving.set(false);}});}
 saveSectionAndCategory():void{if(!this.eventId||!this.layout()){this.error.set('Save the stage configuration first.');return;}this.saving.set(true);this.error.set('');this.domain.saveSections(this.eventId,{id:this.section()?.id??null,name:this.sectionName,code:this.sectionCode,rowCount:this.safeRows,columnCount:this.safeColumns,x:80,y:210,width:740,height:350,displayOrder:1,isAccessibleSection:false,isEnabled:true}).subscribe({next:(section)=>{this.section.set(section);this.domain.saveCategories(this.eventId,{id:this.category()?.id??null,name:this.categoryName,code:this.categoryCode,price:Number(this.categoryPrice)||0,displayOrder:1,isActive:true}).subscribe({next:(category)=>{this.category.set(category);this.saving.set(false);this.status.set('Section and price category saved');},error:(error)=>{this.error.set(httpErrorMessage(error,'The price category could not be saved.'));this.saving.set(false);}});},error:(error)=>{this.error.set(httpErrorMessage(error,'The seating section could not be saved.'));this.saving.set(false);}});}
 generateSeats():void{const section=this.section();const category=this.category();if(!this.eventId||!section||!category){this.error.set('Save the stage, section and category before generating seats.');return;}this.saving.set(true);this.error.set('');this.domain.generateSeats(this.eventId,{sectionId:section.id,seatCategoryId:category.id,rowCount:this.safeRows,columnCount:this.safeColumns,startingRowLabel:'A',startingSeatNumber:1,startX:110,startY:255,horizontalSpacing:Math.max(24,650/this.safeColumns),verticalSpacing:Math.max(24,285/this.safeRows),unavailablePositions:[],accessiblePositions:[],gaps:[]}).subscribe({next:(seats)=>{this.generated.set(seats.length);this.saving.set(false);this.status.set(`${seats.length} seats generated`);},error:(error)=>{this.error.set(httpErrorMessage(error,'Seats could not be generated.'));this.saving.set(false);}});}
 publish():void{if(!this.eventId||!this.generated()){this.error.set('Generate and review the seats before publishing.');return;}this.saving.set(true);this.domain.publishLayout(this.eventId,{publish:true}).subscribe({next:(layout)=>{this.layout.set(layout);this.saving.set(false);this.status.set('Published layout');},error:(error)=>{this.error.set(httpErrorMessage(error,'The layout could not be published.'));this.saving.set(false);}});}
 private geometry():{x:number;y:number;w:number;h:number}{switch(this.selectedStage){case 1:return{x:300,y:65,w:300,h:125};case 4:return{x:330,y:55,w:240,h:190};case 5:return{x:350,y:80,w:200,h:380};case 6:return{x:350,y:100,w:200,h:200};default:return{x:245,y:55,w:410,h:95};}}
}
